name: Build Lean's OpenWRT (IPK Packages)

on:
  push:
    branches: [ master ]
  pull_request:
#

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 仅编译 IPK 时间较短

    steps:
      - name: Checkout Lean's LEDE
        uses: actions/checkout@v4
        with:
          repository: coolsnowwolf/lede
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache flex gawk gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip zlib1g-dev

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a



      - name: Build packages (IPK)
        run: |
          make package/compile -j$(($(nproc) + 1))  # 仅编译软件包
          make package/index  # 生成 Packages 索引

      - name: Upload IPK files
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-ipk-packages
          path: |
            bin/packages/**/*.ipk
            bin/targets/**/packages/*.ipk
